### ISSUE TITLE
Problem with NSInvalidArgumentException

### ISSUE THREAD

**Issue by ellistev** [mthongvanh/SwiftGimbal#1]
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* setObjectForKey: object cannot be nil (key: app_id)'
**\* First throw call stack:

seems to occur when FYX.startServiceAndAuthorizeWithViewController(currentViewController, delegate: self) is being called. 

Maybe I have some of the Gimbal application settings incorrectly entered?

**Comment by mthongvanh** [comment]
Thanks for catching this Steve. It was a problem with the code. I fixed it, so it should be working now.
